apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auto-trade-ai
  labels:
    cloud.googleapis.com/location: asia-northeast1
    run.googleapis.com/cpu-throttling: "false"
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/auto-trade-ai:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: production
        - name: DEBUG
          value: "false"
        - name: DATABASE_URL
          value: sqlite:///tmp/trading.db
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true