steps:
  # 步驟 1: 建置 Docker 映像檔，並傳入建置參數
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-trading-repo/ai-trading-system-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_WS_URL=${_NEXT_PUBLIC_WS_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_JWT_SECRET=${_NEXT_PUBLIC_JWT_SECRET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_ENVIRONMENT=${_NEXT_PUBLIC_ENVIRONMENT}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FEATURE_AI_ANALYSIS=${_NEXT_PUBLIC_FEATURE_AI_ANALYSIS}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FEATURE_REDEMPTION=${_NEXT_PUBLIC_FEATURE_REDEMPTION}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FEATURE_TAIWAN_STOCKS=${_NEXT_PUBLIC_FEATURE_TAIWAN_STOCKS}'
      - './frontend'  # 指定 Dockerfile 位於 frontend 目錄下
    id: 'Build Frontend'

  # 步驟 2: 將映像檔推送到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-trading-repo/ai-trading-system-frontend:$COMMIT_SHA'
    id: 'Push Frontend'

  # 步驟 3: 將建置好的映像檔部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-trading-system-frontend' # 您的 Cloud Run 服務名稱
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-trading-repo/ai-trading-system-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # 為執行的服務設定環境變數 (注意: 格式與 build-arg 不同)
      - '--set-env-vars'
      - '^##^NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}##NEXT_PUBLIC_WS_URL=${_NEXT_PUBLIC_WS_URL}##NEXT_PUBLIC_ENVIRONMENT=${_NEXT_PUBLIC_ENVIRONMENT}##NEXT_PUBLIC_FEATURE_AI_ANALYSIS=${_NEXT_PUBLIC_FEATURE_AI_ANALYSIS}##NEXT_PUBLIC_FEATURE_REDEMPTION=${_NEXT_PUBLIC_FEATURE_REDEMPTION}##NEXT_PUBLIC_FEATURE_TAIWAN_STOCKS=${_NEXT_PUBLIC_FEATURE_TAIWAN_STOCKS}'
    id: 'Deploy Frontend'

# 定義此建置流程會產出的映像檔
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-trading-repo/ai-trading-system-frontend:$COMMIT_SHA'

# 為變數提供預設值
substitutions:
  _NEXT_PUBLIC_API_URL: 'https://ai-trading-system-610357573971.asia-northeast1.run.app'
  _NEXT_PUBLIC_WS_URL: 'wss://ai-trading-system-610357573971.asia-northeast1.run.app'
  _NEXT_PUBLIC_JWT_SECRET: 'e8b7f2d9a6c3e5b8a1d4f6c9b0a3e7d4f9a1b3c5d7e9f0a2b4c6d8e0f1a3b5c7'
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: '729797924622-bj3u88k1l1qfm4du06af75pibmsf7g8p.apps.googleusercontent.com'
  _NEXT_PUBLIC_ENVIRONMENT: 'production'
  _NEXT_PUBLIC_FEATURE_AI_ANALYSIS: 'true'
  _NEXT_PUBLIC_FEATURE_REDEMPTION: 'true'
  _NEXT_PUBLIC_FEATURE_TAIWAN_STOCKS: 'true'

# 建置選項
options:
  logging: CLOUD_LOGGING_ONLY
