# Development environment override
version: '3.8'

services:
  # Override main app for development
  trading_app:
    build:
      target: development
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      ENVIRONMENT: development
    volumes:
      # Mount source code for live reloading
      - .:/app
      - /app/node_modules  # Exclude node_modules if any
    command: ["python", "-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
      - "8888:8888"  # For Jupyter notebook if needed

  # PostgreSQL with more relaxed settings for development
  postgres:
    environment:
      POSTGRES_DB: trading_db_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./sql/dev_init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis without password for easier development
  redis:
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # PgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trading_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trading.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trading_network

  # Redis Commander for Redis management
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: trading_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - trading_network

  # Jupyter notebook for data analysis
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: trading_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "trading123"
    volumes:
      - .:/home/jovyan/work
      - jupyter_data:/home/jovyan
    ports:
      - "8888:8888"
    networks:
      - trading_network

volumes:
  postgres_dev_data:
  redis_dev_data:
  pgadmin_data:
  jupyter_data: