[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.core"

[deploy]
restartPolicyType = "ON_FAILURE"

[variables]
ENVIRONMENT = "production"
DEBUG = "false"
SERVICE_NAME = "core-api"
CHART_SERVICE_URL = "https://chart-service-production.up.railway.app"