[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
# Railway will auto-provide PORT
ENVIRONMENT = "production"
DEBUG = "false"